openapi: 3.1.0
info:
  title: My API
  version: 1.0.0
paths:
  /hello:
    get:
      responses:
        '200':
          description: Successful hello response
          content:
            text/plain:
              schema:
                type: string
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Successful Manager creation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Manager'
components:
  schemas:
    User:
      type: object
      properties:
        name:
          type: string
        age:
          type: integer
      required:
        - name
        - age
    Manager:
      type: object
      properties:
        name:
          type: string
        age:
          type: integer
        user:
          $ref: '#/components/schemas/User'
      required:
        - name
        - age
        - user
