openapi: 3.1.0
info:
  title: My API
  version: 1.0.0
paths:
  /users:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: success
          
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
